---
- hosts: "master workers"
  become: yes
  tasks:
  - name: Disabling Swap on all nodes
    become: yes
    shell:  swapoff -a
  - name: Commenting Swap entries in /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '(^/.*swap*)'
      replace: '# \1'
  - name: Ensure br_netfilter is enabled.
    modprobe:
      name: br_netfilter
      state: present
  - name: update kernel settings
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
  - name: updating the /etc/hosts file
    shell: |
      cat > /etc/hosts <<EOF
      192.168.100.150 eoc-controller
      192.168.100.151 eoc-node1
      192.168.100.152 eoc-node2
      127.0.0.1 localhost
      EOF
  - name: "Installing Docker Prerequisite packages"
    dnf:
      name:
        - epel-release
        - yum-utils
      state: latest
  - name: "Configuring docker-ce repo"
    get_url:
      url: "https://download.docker.com/linux/centos/docker-ce.repo"
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
   - name: " Installing Docker latest version"
    become: yes
    command: dnf install docker-ce -y --allowerasing
  - name: "Configaure the daemon.json to add  Docker's cgroup Driver"
    shell: |
      mkdir -p /etc/docker /etc/systemd/system/docker.service.d
      cat > /etc/docker/daemon.json <<EOF
      {
       "exec-opts": ["native.cgroupdriver=systemd"],
       "log-driver": "json-file",
       "log-opts": {
       "max-size": "100m"
       },
       "storage-driver": "overlay2",
       "storage-opts": [
       "overlay2.override_kernel_check=true"
       ]
      }
      EOF
  - name: "Starting Docker Service"
    service:
      name: "docker"
      state: started
      enabled: yes
  - name: Add Kubernetes repository
    yum_repository:
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      name: "Kubernetes"
      state: present
      description: "Kubernetes Repository"
      gpgcheck: yes
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      # exclude: "kubelet kubeadm kubectl"
  - name: "Installing Kubeadm, Kubelet, and Kubectl"
    dnf:
      name:
        - kubectl-1.23.0-00
        - kubeadm-1.23.0-00
        - kubelet-1.23.0-00
      state: present
   
